---
alg: lstm
base_dir: logs/pretrained/Abilene
log_level: INFO
gpu: 0
mon_ratio: 0.1
scaler: MM
data:
  batch_size: 512
  dataset_dir: Dataset/Abilene2d.npy
  val_batch_size: 1
  eval_batch_size: 1
  test_batch_size: 1
  data_name: Abilene
  day_size: 288
  data_size: 1.0
model:
  model_type: lstm
  horizon: 1
  input_dim: 2
  num_nodes: 144
  output_dim: 1
  rnn_units: 64
  seq_len: 36
train:
  dropout: 0
  epochs: 50000
  optimizer: adam
  patience: 50
  continue_train: True
test:
  run_times: 50
  flow_selection: Random
