---
alg: dcrnn
base_dir: logs/pretrained/Abilene
log_level: INFO
gpu: 0
mon_ratio: 0.5
scaler: MM
seed: 153
data:
  data_name: Abilene
  batch_size: 256
  data_dir: Dataset/
  adj_method: OD
  day_size: 288
  data_size: 1.0
  generate_data: False
model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 1
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 1
  num_nodes: 144
  num_rnn_layers: 1
  output_dim: 1
  rnn_units: 32
  seq_len: 36
  use_curriculum_learning: true
train:
  base_lr: 0.005
  dropout: 0.5
  epoch: 64
  epochs: 50000
  epsilon: 0.00000001
  global_step: 24375
  lr_decay_ratio: 0.05
  max_grad_norm: 1
  max_to_keep: 300
  min_learning_rate: 0.0005
  optimizer: adam
  patience: 30
  steps:
    - 50
    - 100
    - 150
    - 200
  test_every_n_epochs: 10
  results_path: results/
  results_name: Abilene-dgc-lstm
  continue_train: True
test:
  run_times: 50
  flow_selection: Random