---
alg: lstm
base_dir: logs/pretrained/Abilene
log_level: INFO
gpu: 0
mon_ratio: 0.5
scaler: MM
seed: 153
data:
  data_name: Abilene
  batch_size: 512
  data_dir: Dataset/
  day_size: 288
model:
  model_type: lstm
  horizon: 1
  input_dim: 2
  num_nodes: 144
  output_dim: 1
  rnn_units: 64
  seq_len: 36
train:
  dropout: 0.5
  epochs: 50000
  optimizer: adam
  patience: 50
  continue_train: True
test:
  run_times: 50
  flow_selection: Random
