---
base_dir: data/model
log_level: INFO
gpu: 1
mon_ratio: 0.3
data:
  batch_size: 64
  raw_dataset_dir: Dataset/Abilene2d.npy
  dataset_dir: Dataset/Abilene2d/
  graph_pkl_filename: Dataset/Abilene2d/Abilene-adj-mx
  norm_data_path: Dataset/Abilene2d/
  test_batch_size: 64
  data_name: Abilene
  Abilene_day_size: 288
  generate_data: True
model:
  cl_decay_steps: 2000
  filter_type: dual_random_walk
  horizon: 3
  input_dim: 2
  l1_decay: 0
  max_diffusion_step: 2
  num_nodes: 144
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 64
  seq_len: 36
  use_curriculum_learning: true
train:
  base_lr: 0.0001
  dropout: 0
  epoch: 64
  epochs: 100
  epsilon: 0.001
  global_step: 24375
  log_dir: logs/pretrained/Abilene/
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 50
  steps:
    - 20
    - 30
    - 40
    - 50
  test_every_n_epochs: 10
  results_path: results/
  results_name: Abilene-dgc-lstm
