---
alg: LSTM-ED
base_dir: logs/pretrained/Abilene
log_level: INFO
gpu: 0
mon_ratio: 0.3
scaler: MM
data:
  batch_size: 512
  raw_dataset_dir: Dataset/Abilene2d.npy
  val_batch_size: 1
  eval_batch_size: 1
  test_batch_size: 1
  data_name: Abilene
  day_size: 288
  data_size: 1.0
model:
  model_type: ed
  horizon: 3
  input_dim: 2
  l1_decay: 0
  num_nodes: 144
  output_dim: 1
  rnn_units: 64
  seq_len: 36
train:
  base_lr: 0.01
  dropout: 0
  epochs: 50000
  epsilon: 0.001
  optimizer: adam
  patience: 30
test:
  run_times: 50
  flow_selection: Random
