---
alg: CONV_LSTM
base_dir: logs/pretrained/Abilene
log_level: INFO
gpu: 0
mon_ratio: 0.3
data:
  batch_size: 512
  raw_dataset_dir: Dataset/Abilene2d.npy
  dataset_dir: Dataset/Abilene2d/conv_lstm/seq_36/
  eval_batch_size: 1
  data_name: Abilene
  day_size: 288
  generate_data: False
  data_size: 1.0
model:
  cl_decay_steps: 2000
  horizon: 3
  input_dim: 2
  l1_decay: 0
  num_nodes: 144
  num_rnn_layers: 2
  output_dim: 1
  rnn_units: 64
  seq_len: 36
train:
  base_lr: 0.01
  dropout: 0
  epoch: 64
  epochs: 50000
  epsilon: 0.001
  global_step: 24375
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 30
  test_every_n_epochs: 10
  results_name: Abilene-dgc-lstm
  continue_train: False
test:
  run_times: 50
  flow_selection: Random
  test_size: 2